version: '3.0'
services:
  connector:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-chess-connector:latest
    ports:
      - "8000:8000"
                                   
  asciichessts:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-chess-asciichessts:latest
    ports:
      - "3838:80"

x-aws-vpc: "${AWS_VPC_ID}"
x-aws-subnets: ["${AWS_SUBNET_ID_1}", "${AWS_SUBNET_ID_2}"]
x-aws-securitygroup: ["${AWS_SECURITY_GROUP_ID}"]
