version: '3.0'
services:
  connector:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-chess-connector:latest
    ports:
      - "8000:8000"
                                   
  asciichessr:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-chess-asciichessr:latest
    ports:
      - "3838:3838"

x-aws-vpc: "vpc-fae8de82"  
x-aws-subnets: ["subnet-29cb6763", "subnet-d24ecdaa"]  
x-aws-securitygroup: ["sg-bb4e128b"]  
