version: '3.0'
services:
  connector:
    build:
      context: ./connector
    ports:
      - "8000:8000"
    networks:
      - chessnet
                                   
  asciichessts:
    build:
      context: ./ascii-chess-ts
    ports:
     - "3838:80"
    depends_on:
      - connector
    networks:
      - chessnet

  prototype-shiny:
    build:
      context: ./prototype-shiny
    ports:
      - "3839:3838"
    depends_on:
      - connector
    environment:
      - SHINY_ENVIRONMENT=production
    networks:
      - chessnet
                                   
networks:
  chessnet:
