version: '3.0'
services:
  connector:
    build:
      context: ./connector
    ports:
      - "8000:8000"
    networks:
      - chessnet
                                   
  asciichessr:
    build:
      context: ./asciiChessR
    ports:
      - "3838:3838"
    depends_on:
      - connector
    networks:
      - chessnet
                                   
networks:
  chessnet:

