version: '3.0'
services:
  connector:
    build:
      context: ./connector
    ports:
      - "8000:8000"
    networks:
      - chessnet
                                   
  asciichessts:
    build:
      context: ./ascii-chess-ts
    ports:
     - "3838:80"
    depends_on:
      - connector
    networks:
      - chessnet
                                   
networks:
  chessnet:

