export const FETCH_CHESS_COM_DAILY_PUZZLE_REQUEST =
    "FETCH_CHESS_COM_DAILY_PUZZLE_REQUEST";
export const FETCH_CHESS_COM_DAILY_PUZZLE_SUCCESS =
    "FETCH_CHESS_COM_DAILY_PUZZLE_SUCCESS";
export const FETCH_CHESS_COM_DAILY_PUZZLE_FAILURE =
    "FETCH_CHESS_COM_DAILY_PUZZLE_FAILURE";
