note: {
  shape: page
  style: {
    font-size: 26
  }
}
edge_invis: {
  style: {
    stroke-width: 0
  }
}
edge_request: {
  label: rq
  style: {
    font-color: crimson
    stroke-dash: 5
    stroke: black
  }
}
edge_response: {
  label: rsp
  style: {
    font-color: crimson
    stroke-dash: 3
    stroke: deepskyblue
  }
}
obj_load_balancer: {
  shape: hexagon
  icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Load%20Balancing.svg
  style: {
    font-size: 20
    fill: burlywood
  }
}
obj_server: {
  style: {
    font-size: 20
    fill: darkmagenta
    font-color: white
  }
}
obj_target_group: {
  style: {
    fill: lightblue
  }
}
